sudo: required

language: python

services:
  - docker

python:
  - 3.6

# addons:
#   sauce_connect: true

before_script:
  - docker-compose -f docker-compose.travis.yml up --build -d
  - docker ps -a
  - sleep 30  # wait for PostgreSQl and Elasticsearch to start

script: ./scripts/runtests.sh

after_script:
  - docker-compose -f docker-compose.travis.yml down
