# Creates a minimal stack for local development of Cyphon. It opens
# ports on your host machine to make backend services accessible through
# `localhost`.

version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VER}
    env_file:
      - ./config-COPYME/env/cyphon.env
    ports:
      - "9200:9200"
    volumes:
      - ./config-COPYME/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./config-COPYME/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - ./config-COPYME/elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro

  mongo:
    image: mongo:${MONGODB_VER}
    env_file:
      - ./config-COPYME/env/cyphon.env
    ports:
      - "27017:27017"

  postgres:
    image: mdillon/postgis:${POSTGRES_VER}
    env_file:
      - ./config-COPYME/env/cyphon.env
    ports:
      - "5432:5432"
