# Production overrides that will: 
# 
#   - map container ports to the same ports on the host machine
#   - map container volumes to volumes on the host machine
# 

version: '2'

services:

  elasticsearch:
    volumes:
      - ../data/elasticsearch:/usr/share/elasticsearch/data

  logstash:
    ports:
      - "5044:5044"
      - "5045:5045"  # you can configure Filebeat to send Nessus files here

  # mongo:
  #   volumes:
  #     - ../data/mongodb:/data/db

  nginx:
    ports:
      - "80:80"        # Cyphon
      - "443:443"      # Cyphon
      - "5601:5601"    # Kibana
      - "15672:15672"  # RabbitMQ management plugin

  postgres:
    volumes:
      - ../data/postgresql:/var/lib/postgresql/data
